import type { ThemeConfig } from "antd";

const fontFamily =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'PingFang SC', 'Microsoft YaHei', 'Noto Sans CJK SC', 'Noto Sans', sans-serif";

export const qtableTokens = {
  color: {
    primary: "#2563EB",
    primaryHover: "#1D4ED8",
    primaryActive: "#1E40AF",
    primarySoft: "#EFF6FF",
    primaryBorder: "#BFDBFE",
    primarySelection: "rgba(37, 99, 235, 0.08)",
    text: "#111827",
    textSecondary: "#667085",
    textTertiary: "#98A2B3",
    border: "#EAECF0",
    borderStrong: "#D0D5DD",
    background: "#FFFFFF",
    backgroundLayout: "#F8FAFC",
    surfaceHover: "#F9FAFB",
    success: "#16A34A",
    successSoft: "#F0FDF4",
    warning: "#D97706",
    warningSoft: "#FFFBEB",
    danger: "#DC2626",
    dangerSoft: "#FEF2F2",
    ai: "#7C3AED",
    aiSoft: "#F5F3FF",
    focusRing: "rgba(37, 99, 235, 0.36)",
  },
  typography: {
    fontFamily,
    size: {
      pageTitle: 24,
      sectionTitle: 18,
      body: 14,
      table: 13,
      label: 12,
      micro: 11,
    },
    lineHeight: {
      pageTitle: 32,
      sectionTitle: 24,
      body: 22,
      table: 20,
      label: 18,
      micro: 16,
    },
  },
  space: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 12,
    pill: 999,
  },
  size: {
    appBar: 64,
    controlCompact: 32,
    control: 36,
    controlPrimary: 40,
    tableRowCompact: 36,
    tableRow: 44,
    tableRowComfortable: 52,
  },
  shadow: {
    card: "0 1px 2px rgba(16, 24, 40, 0.04)",
    floating: "0 12px 32px rgba(15, 23, 42, 0.12)",
    focus: "0 0 0 3px rgba(37, 99, 235, 0.18)",
  },
} as const;

export const qtableTheme: ThemeConfig = {
  token: {
    colorPrimary: qtableTokens.color.primary,
    colorPrimaryHover: qtableTokens.color.primaryHover,
    colorPrimaryActive: qtableTokens.color.primaryActive,
    colorLink: qtableTokens.color.primary,
    colorSuccess: qtableTokens.color.success,
    colorWarning: qtableTokens.color.warning,
    colorError: qtableTokens.color.danger,
    colorText: qtableTokens.color.text,
    colorTextSecondary: qtableTokens.color.textSecondary,
    colorBorder: qtableTokens.color.border,
    colorBorderSecondary: qtableTokens.color.border,
    colorBgBase: qtableTokens.color.background,
    colorBgContainer: qtableTokens.color.background,
    colorBgLayout: qtableTokens.color.backgroundLayout,
    borderRadius: qtableTokens.radius.sm,
    borderRadiusLG: qtableTokens.radius.md,
    borderRadiusSM: qtableTokens.radius.sm,
    controlHeight: qtableTokens.size.control,
    controlHeightSM: qtableTokens.size.controlCompact,
    fontFamily: qtableTokens.typography.fontFamily,
    fontSize: qtableTokens.typography.size.body,
    lineHeight: qtableTokens.typography.lineHeight.body / qtableTokens.typography.size.body,
    boxShadowSecondary: qtableTokens.shadow.floating,
  },
};

export const qtableCssVariables: Record<string, string> = {
  "--qtable-color-primary": qtableTokens.color.primary,
  "--qtable-color-primary-hover": qtableTokens.color.primaryHover,
  "--qtable-color-primary-active": qtableTokens.color.primaryActive,
  "--qtable-color-primary-soft": qtableTokens.color.primarySoft,
  "--qtable-color-primary-border": qtableTokens.color.primaryBorder,
  "--qtable-color-primary-selection": qtableTokens.color.primarySelection,
  "--qtable-color-text": qtableTokens.color.text,
  "--qtable-color-text-secondary": qtableTokens.color.textSecondary,
  "--qtable-color-text-tertiary": qtableTokens.color.textTertiary,
  "--qtable-color-border": qtableTokens.color.border,
  "--qtable-color-border-strong": qtableTokens.color.borderStrong,
  "--qtable-color-background": qtableTokens.color.background,
  "--qtable-color-background-layout": qtableTokens.color.backgroundLayout,
  "--qtable-color-surface-hover": qtableTokens.color.surfaceHover,
  "--qtable-color-success": qtableTokens.color.success,
  "--qtable-color-success-soft": qtableTokens.color.successSoft,
  "--qtable-color-warning": qtableTokens.color.warning,
  "--qtable-color-warning-soft": qtableTokens.color.warningSoft,
  "--qtable-color-danger": qtableTokens.color.danger,
  "--qtable-color-danger-soft": qtableTokens.color.dangerSoft,
  "--qtable-color-ai": qtableTokens.color.ai,
  "--qtable-color-ai-soft": qtableTokens.color.aiSoft,
  "--qtable-color-focus-ring": qtableTokens.color.focusRing,
  "--qtable-font-family": qtableTokens.typography.fontFamily,
  "--qtable-font-size-page-title": `${qtableTokens.typography.size.pageTitle}px`,
  "--qtable-font-size-section-title": `${qtableTokens.typography.size.sectionTitle}px`,
  "--qtable-font-size-body": `${qtableTokens.typography.size.body}px`,
  "--qtable-font-size-table": `${qtableTokens.typography.size.table}px`,
  "--qtable-font-size-label": `${qtableTokens.typography.size.label}px`,
  "--qtable-font-size-micro": `${qtableTokens.typography.size.micro}px`,
  "--qtable-line-height-body": `${qtableTokens.typography.lineHeight.body}px`,
  "--qtable-line-height-table": `${qtableTokens.typography.lineHeight.table}px`,
  "--qtable-line-height-label": `${qtableTokens.typography.lineHeight.label}px`,
  "--qtable-space-1": `${qtableTokens.space[1]}px`,
  "--qtable-space-2": `${qtableTokens.space[2]}px`,
  "--qtable-space-3": `${qtableTokens.space[3]}px`,
  "--qtable-space-4": `${qtableTokens.space[4]}px`,
  "--qtable-space-5": `${qtableTokens.space[5]}px`,
  "--qtable-space-6": `${qtableTokens.space[6]}px`,
  "--qtable-radius-sm": `${qtableTokens.radius.sm}px`,
  "--qtable-radius-md": `${qtableTokens.radius.md}px`,
  "--qtable-radius-lg": `${qtableTokens.radius.lg}px`,
  "--qtable-radius-pill": `${qtableTokens.radius.pill}px`,
  "--qtable-size-app-bar": `${qtableTokens.size.appBar}px`,
  "--qtable-size-control-compact": `${qtableTokens.size.controlCompact}px`,
  "--qtable-size-control": `${qtableTokens.size.control}px`,
  "--qtable-size-control-primary": `${qtableTokens.size.controlPrimary}px`,
  "--qtable-size-table-row-compact": `${qtableTokens.size.tableRowCompact}px`,
  "--qtable-size-table-row": `${qtableTokens.size.tableRow}px`,
  "--qtable-size-table-row-comfortable": `${qtableTokens.size.tableRowComfortable}px`,
  "--qtable-shadow-card": qtableTokens.shadow.card,
  "--qtable-shadow-floating": qtableTokens.shadow.floating,
  "--qtable-shadow-focus": qtableTokens.shadow.focus,
};

export function installQTableCssVariables(
  root: HTMLElement = document.documentElement,
) {
  Object.entries(qtableCssVariables).forEach(([name, value]) => {
    root.style.setProperty(name, value);
  });
}
